name: "release"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: deps
        run: npm i release-it @release-it/conventional-changelog

      - name: release-it
        uses: TheRealWaldo/release-it@v0.7.2
        with:
          json-opts: '{"dry-run": true}'
