name: "release"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install Dependencies
        run: npm ci

      - name: Run Release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
